
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain grid-circles-strips)
    (:requirements )
    (:types
        cell - object
    )

    (:predicates
        (reward ?x1 - cell)
        (at ?x1 - cell)
        (adjacent ?x1 - cell ?x2 - cell)
        (blocked ?x1 - cell)
    )

    (:functions
        
    )

    
    (:action move
     :parameters (?from - cell ?to - cell)
     :precondition (and (and (adjacent ?from ?to) (at ?from)) (not (blocked ?to)))
     :effect (and
        (not (at ?from))
        (at ?to))
    ) 


    (:action pick-reward
     :parameters (?x - cell)
     :precondition (and (at ?x) (reward ?x))
     :effect (and
        (not (reward ?x)))
    ) 


)