
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain gridworld)
    (:requirements :numeric-fluents)
    (:types
        coordinate - int
    )

    (:predicates
        
    )

    (:functions
        (Y ) - coordinate
        (X ) - coordinate
    )

    
    (:action move-up
     :parameters ()
     :precondition (< (Y ) 10)
     :effect (and
        (assign (Y ) (+ (Y ) 1)))
    ) 


    (:action move-down
     :parameters ()
     :precondition (> (Y ) 1)
     :effect (and
        (assign (Y ) (- (Y ) 1)))
    ) 


    (:action move-left
     :parameters ()
     :precondition (> (X ) 1)
     :effect (and
        (assign (X ) (- (X ) 1)))
    ) 


    (:action move-right
     :parameters ()
     :precondition (< (X ) 10)
     :effect (and
        (assign (X ) (+ (X ) 1)))
    ) 

)