
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem gridworld-10x10)
    (:domain gridworld-strips)

    (:objects
        c1 c10 c2 c3 c4 c5 c6 c7 c8 c9 - coordinate
    )

    (:init
        (= (maxpos ) c10)
        (= (ypos ) c1)
        (= (xpos ) c1)
        (succ c6 c7)
        (succ c9 c10)
        (succ c5 c6)
        (succ c3 c4)
        (succ c1 c2)
        (succ c7 c8)
        (succ c4 c5)
        (succ c2 c3)
        (succ c8 c9)
    )

    (:goal
        (and (= (xpos ) c10) (= (ypos ) c10))
    )

    
    
    
)

