
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem gridworld-10x10)
    (:domain gridworld)

    (:objects
        
    )

    (:init
        (= (maxpos ) 10)
        (= (ypos ) 1)
        (= (xpos ) 1)
    )

    (:goal
        (and (= (xpos ) 10) (= (ypos ) 10))
    )

    
    (:bounds
        (coordinate - int[1..10]))
    
)

