
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem 10x10)
    (:domain grid-circles)

    (:objects
        
    )

    (:init
        (= (X ) 1)
        (= (Y ) 10)
    )

    (:goal
        (and (= (X ) 2) (= (Y ) 3))
    )

    
    
    
)

