
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem gridworld-5x5)
    (:domain gridworld-strips)

    (:objects
        c1 c2 c3 c4 c5 - coordinate
    )

    (:init
        (= (maxpos ) c5)
        (= (ypos ) c1)
        (= (xpos ) c1)
        (succ c3 c4)
        (succ c1 c2)
        (succ c4 c5)
        (succ c2 c3)
    )

    (:goal
        (and (= (xpos ) c3) (= (ypos ) c4))
    )

    
    
    
)

