
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem gridworld-3x3)
    (:domain gridworld)

    (:objects
        
    )

    (:init
        (= (maxpos ) 3)
        (= (ypos ) 1)
        (= (xpos ) 1)
    )

    (:goal
        (and (= (xpos ) 3) (= (ypos ) 3))
    )

    
    (:bounds
        (coordinate - int[1..3]))
    
)

