
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem gridworld-5x5)
    (:domain gridworld)

    (:objects
        
    )

    (:init
        (= (maxpos ) 5)
        (= (ypos ) 1)
        (= (xpos ) 1)
    )

    (:goal
        (and (= (xpos ) 5) (= (ypos ) 5))
    )

    
    (:bounds
        (coordinate - int[1..5]))
    
)

