
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem gridworld-7x7)
    (:domain gridworld)

    (:objects
        
    )

    (:init
        (= (maxpos ) 7)
        (= (ypos ) 1)
        (= (xpos ) 1)
    )

    (:goal
        (and (= (xpos ) 7) (= (ypos ) 7))
    )

    
    (:bounds
        (coordinate - int[1..7]))
    
)

