
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain taxi-fs)
    (:requirements :numeric-fluents)
    (:types
        cell - object
    )

    (:constants
        inside_taxi - cell
    )

    (:predicates
        (adjacent ?x1 - cell ?x2 - cell)
    )

    (:functions
        (loct ) - cell
        (locp ) - cell
    )

    
    (:action pick-passenger
     :parameters ()
     :precondition (= (locp ) (loct ))
     :effect (and
        (assign (locp ) inside_taxi))
    ) 


    (:action drop-passenger
     :parameters ()
     :precondition (= (locp ) inside_taxi)
     :effect (and
        (assign (locp ) (loct )))
    ) 


    (:action move
     :parameters (?to - cell)
     :precondition (adjacent (loct ) ?to)
     :effect (and
        (assign (loct ) ?to))
    ) 


    (:action noop
     :parameters (?x - cell)
     :precondition (= (loct ) ?x)
     :effect (and
        (assign (loct ) ?x))
    ) 

)