(define (problem BLOCKS-5-CLEAR-X)
(:domain BLOCKS)
(:objects A B C D E F G)
(:init (ON C B) (ON D C) (ONTABLE B) (CLEAR D)
       ;; (HOLDING A)
       (CLEAR A) (ONTABLE A)
       (HANDEMPTY )
)
(:goal (AND (ON A B)))
)
