CXX=clang++


build_alt_theory:	build_alt_theory.cc
			$(CXX) -std=c++11 -o build_alt_theory build_alt_theory.cc

debug:			build_alt_theory.cc
			$(CXX) -g -std=c++11 -o build_alt_theory.d build_alt_theory.cc
